INSERT INTO actor (name, age) VALUES ('Tim Robbins', 58);
INSERT INTO actor (name, age) VALUES ('Morgan Freeman', 25);
INSERT INTO actor (name, age) VALUES ('Bob Gunton', 43);
INSERT INTO actor (name, age) VALUES ('William Sadler', 58);
INSERT INTO actor (name, age) VALUES ('Marlon Brando', 24);
INSERT INTO actor (name, age) VALUES ('Al Pacino', 51);
INSERT INTO actor (name, age) VALUES ('James Caan', 45);
INSERT INTO actor (name, age) VALUES ('Richard S  Castellano', 38);
INSERT INTO actor (name, age) VALUES ('Al Pacino', 34);
INSERT INTO actor (name, age) VALUES ('Robert Duvall', 24);
INSERT INTO actor (name, age) VALUES ('Diane Keaton', 50);
INSERT INTO actor (name, age) VALUES ('Robert De Niro', 44);
INSERT INTO actor (name, age) VALUES ('Christian Bale', 58);
INSERT INTO actor (name, age) VALUES ('Heath Ledger', 21);
INSERT INTO actor (name, age) VALUES ('Aaron Eckhart', 36);
INSERT INTO actor (name, age) VALUES ('Michael Caine', 22);
INSERT INTO actor (name, age) VALUES ('Martin Balsam', 27);
INSERT INTO actor (name, age) VALUES ('John Fiedler', 23);
INSERT INTO actor (name, age) VALUES ('Lee J  Cobb', 51);
INSERT INTO actor (name, age) VALUES ('E G  Marshall', 52);
INSERT INTO actor (name, age) VALUES ('Liam Neeson', 39);
INSERT INTO actor (name, age) VALUES ('Ben Kingsley', 34);
INSERT INTO actor (name, age) VALUES ('Ralph Fiennes', 48);
INSERT INTO actor (name, age) VALUES ('Caroline Goodall', 44);
INSERT INTO actor (name, age) VALUES ('Noel Appleby', 43);
INSERT INTO actor (name, age) VALUES ('Ali Astin', 40);
INSERT INTO actor (name, age) VALUES ('Sean Astin', 45);
INSERT INTO actor (name, age) VALUES ('David Aston', 23);
INSERT INTO actor (name, age) VALUES ('Tim Roth', 43);
INSERT INTO actor (name, age) VALUES ('Amanda Plummer', 26);
INSERT INTO actor (name, age) VALUES ('Laura Lovelace', 55);
INSERT INTO actor (name, age) VALUES ('John Travolta', 27);
INSERT INTO actor (name, age) VALUES ('Edward Norton', 26);
INSERT INTO actor (name, age) VALUES ('Brad Pitt', 28);
INSERT INTO actor (name, age) VALUES ('Meat Loaf', 28);
INSERT INTO actor (name, age) VALUES ('Zach Grenier', 26);
INSERT INTO actor (name, age) VALUES ('Alan Howard', 54);
INSERT INTO actor (name, age) VALUES ('Noel Appleby', 60);
INSERT INTO actor (name, age) VALUES ('Sean Astin', 20);
INSERT INTO actor (name, age) VALUES ('Sala Baker', 50);
INSERT INTO actor (name, age) VALUES ('Tom Hanks', 58);
INSERT INTO actor (name, age) VALUES ('Rebecca Williams', 32);
INSERT INTO actor (name, age) VALUES ('Sally Field', 27);
INSERT INTO actor (name, age) VALUES ('Michael Conner Humphreys', 42);
INSERT INTO actor (name, age) VALUES ('Mark Hamill', 53);
INSERT INTO actor (name, age) VALUES ('Harrison Ford', 23);
INSERT INTO actor (name, age) VALUES ('Carrie Fisher', 20);
INSERT INTO actor (name, age) VALUES ('Billy Dee Williams', 50);
INSERT INTO actor (name, age) VALUES ('Leonardo DiCaprio', 55);
INSERT INTO actor (name, age) VALUES ('Joseph Gordon Levitt', 40);
INSERT INTO actor (name, age) VALUES ('Ellen Page', 55);
INSERT INTO actor (name, age) VALUES ('Tom Hardy', 29);
INSERT INTO actor (name, age) VALUES ('Bruce Allpress', 56);
INSERT INTO actor (name, age) VALUES ('Sean Astin', 44);
INSERT INTO actor (name, age) VALUES ('John Bach', 39);
INSERT INTO actor (name, age) VALUES ('Sala Baker', 37);
INSERT INTO actor (name, age) VALUES ('Michael Berryman', 56);
INSERT INTO actor (name, age) VALUES ('Peter Brocco', 42);
INSERT INTO actor (name, age) VALUES ('Dean R  Brooks', 58);
INSERT INTO actor (name, age) VALUES ('Alonzo Brown', 53);
INSERT INTO actor (name, age) VALUES ('Robert De Niro', 42);
INSERT INTO actor (name, age) VALUES ('Ray Liotta', 52);
INSERT INTO actor (name, age) VALUES ('Joe Pesci', 57);
INSERT INTO actor (name, age) VALUES ('Lorraine Bracco', 55);
INSERT INTO actor (name, age) VALUES ('Keanu Reeves', 32);
INSERT INTO actor (name, age) VALUES ('Laurence Fishburne', 22);
INSERT INTO actor (name, age) VALUES ('Carrie Anne Moss', 59);
INSERT INTO actor (name, age) VALUES ('Hugo Weaving', 27);
INSERT INTO actor (name, age) VALUES ('Mark Hamill', 55);
INSERT INTO actor (name, age) VALUES ('Harrison Ford', 23);
INSERT INTO actor (name, age) VALUES ('Carrie Fisher', 44);
INSERT INTO actor (name, age) VALUES ('Peter Cushing', 20);
INSERT INTO actor (name, age) VALUES ('Morgan Freeman', 48);
INSERT INTO actor (name, age) VALUES ('Andrew Kevin Walker', 40);
INSERT INTO actor (name, age) VALUES ('Kevin Spacey', 55);
INSERT INTO actor (name, age) VALUES ('Daniel Zacapa', 46);
INSERT INTO actor (name, age) VALUES ('James Stewart', 60);
INSERT INTO actor (name, age) VALUES ('Donna Reed', 35);
INSERT INTO actor (name, age) VALUES ('Lionel Barrymore', 29);
INSERT INTO actor (name, age) VALUES ('Thomas Mitchell', 51);
INSERT INTO actor (name, age) VALUES ('Jodie Foster', 39);
INSERT INTO actor (name, age) VALUES ('Lawrence A  Bonney', 45);
INSERT INTO actor (name, age) VALUES ('Kasi Lemmons', 32);
INSERT INTO actor (name, age) VALUES ('Lawrence T  Wrentz', 49);
INSERT INTO actor (name, age) VALUES ('Stephen Baldwin', 29);
INSERT INTO actor (name, age) VALUES ('Gabriel Byrne', 34);
INSERT INTO actor (name, age) VALUES ('Benicio Del Toro', 25);
INSERT INTO actor (name, age) VALUES ('Kevin Pollak', 29);
INSERT INTO actor (name, age) VALUES ('Jean Reno', 48);
INSERT INTO actor (name, age) VALUES ('Gary Oldman', 25);
INSERT INTO actor (name, age) VALUES ('Natalie Portman', 55);
INSERT INTO actor (name, age) VALUES ('Danny Aiello', 43);
INSERT INTO actor (name, age) VALUES ('Tom Hanks', 43);
INSERT INTO actor (name, age) VALUES ('Tom Sizemore', 60);
INSERT INTO actor (name, age) VALUES ('Edward Burns', 40);
INSERT INTO actor (name, age) VALUES ('Barry Pepper', 24);
INSERT INTO actor (name, age) VALUES ('Virginia Cherrill', 53);
INSERT INTO actor (name, age) VALUES ('Florence Lee', 34);
INSERT INTO actor (name, age) VALUES ('Harry Myers', 30);
INSERT INTO actor (name, age) VALUES ('Al Ernest Garcia', 54);
INSERT INTO actor (name, age) VALUES ('Ellen Burstyn', 28);
INSERT INTO actor (name, age) VALUES ('Matthew McConaughey', 44);
INSERT INTO actor (name, age) VALUES ('Mackenzie Foy', 33);
INSERT INTO actor (name, age) VALUES ('John Lithgow', 45);
INSERT INTO actor (name, age) VALUES ('Edward Norton', 49);
INSERT INTO actor (name, age) VALUES ('Edward Furlong', 41);
INSERT INTO actor (name, age) VALUES ('Beverly D Angelo', 52);
INSERT INTO actor (name, age) VALUES ('Jennifer Lien', 58);
INSERT INTO actor (name, age) VALUES ('Charles Chaplin', 44);
INSERT INTO actor (name, age) VALUES ('Paulette Goddard', 32);
INSERT INTO actor (name, age) VALUES ('Henry Bergman', 53);
INSERT INTO actor (name, age) VALUES ('Tiny Sandford', 44);
INSERT INTO actor (name, age) VALUES ('Humphrey Bogart', 27);
INSERT INTO actor (name, age) VALUES ('Ingrid Bergman', 55);
INSERT INTO actor (name, age) VALUES ('Paul Henreid', 25);
INSERT INTO actor (name, age) VALUES ('Claude Rains', 49);
INSERT INTO actor (name, age) VALUES ('Tom Hanks', 36);
INSERT INTO actor (name, age) VALUES ('David Morse', 30);
INSERT INTO actor (name, age) VALUES ('Michael Clarke Duncan', 36);
INSERT INTO actor (name, age) VALUES ('Bonnie Hunt', 30);
INSERT INTO actor (name, age) VALUES ('Anthony Perkins', 49);
INSERT INTO actor (name, age) VALUES ('Vera Miles', 24);
INSERT INTO actor (name, age) VALUES ('John Gavin', 29);
INSERT INTO actor (name, age) VALUES ('Janet Leigh', 60);
INSERT INTO actor (name, age) VALUES ('Harrison Ford', 55);
INSERT INTO actor (name, age) VALUES ('Karen Allen', 51);
INSERT INTO actor (name, age) VALUES ('Paul Freeman', 32);
INSERT INTO actor (name, age) VALUES ('Ronald Lacey', 25);
INSERT INTO actor (name, age) VALUES ('Adrien Brody', 22);
INSERT INTO actor (name, age) VALUES ('Emilia Fox', 55);
INSERT INTO actor (name, age) VALUES ('Michal Zebrowski', 28);
INSERT INTO actor (name, age) VALUES ('Ed Stoppard', 30);
INSERT INTO actor (name, age) VALUES ('James Stewart', 32);
INSERT INTO actor (name, age) VALUES ('Grace Kelly', 46);
INSERT INTO actor (name, age) VALUES ('Wendell Corey', 21);
INSERT INTO actor (name, age) VALUES ('Thelma Ritter', 39);
INSERT INTO actor (name, age) VALUES ('Leonardo DiCaprio', 57);
INSERT INTO actor (name, age) VALUES ('Matt Damon', 57);
INSERT INTO actor (name, age) VALUES ('Jack Nicholson', 23);
INSERT INTO actor (name, age) VALUES ('Mark Wahlberg', 35);
INSERT INTO actor (name, age) VALUES ('Miles Teller', 46);
INSERT INTO actor (name, age) VALUES ('J K  Simmons', 33);
INSERT INTO actor (name, age) VALUES ('Paul Reiser', 33);
INSERT INTO actor (name, age) VALUES ('Melissa Benoist', 23);
INSERT INTO actor (name, age) VALUES ('Arnold Schwarzenegger', 59);
INSERT INTO actor (name, age) VALUES ('Linda Hamilton', 41);
INSERT INTO actor (name, age) VALUES ('Edward Furlong', 54);
INSERT INTO actor (name, age) VALUES ('Robert Patrick', 59);
INSERT INTO actor (name, age) VALUES ('Michael J  Fox', 56);
INSERT INTO actor (name, age) VALUES ('Christopher Lloyd', 50);
INSERT INTO actor (name, age) VALUES ('Lea Thompson', 54);
INSERT INTO actor (name, age) VALUES ('Crispin Glover', 27);
INSERT INTO actor (name, age) VALUES ('Russell Crowe', 39);
INSERT INTO actor (name, age) VALUES ('Joaquin Phoenix', 43);
INSERT INTO actor (name, age) VALUES ('Connie Nielsen', 52);
INSERT INTO actor (name, age) VALUES ('Oliver Reed', 31);
INSERT INTO actor (name, age) VALUES ('Rowan Atkinson', 34);
INSERT INTO actor (name, age) VALUES ('Matthew Broderick', 38);
INSERT INTO actor (name, age) VALUES ('Niketa Calame', 49);
INSERT INTO actor (name, age) VALUES ('Jim Cummings', 30);
INSERT INTO actor (name, age) VALUES ('Hugh Jackman', 60);
INSERT INTO actor (name, age) VALUES ('Christian Bale', 39);
INSERT INTO actor (name, age) VALUES ('Michael Caine', 28);
INSERT INTO actor (name, age) VALUES ('Piper Perabo', 42);
INSERT INTO actor (name, age) VALUES ('Marlon Brando', 37);
INSERT INTO actor (name, age) VALUES ('Martin Sheen', 54);
INSERT INTO actor (name, age) VALUES ('Robert Duvall', 49);
INSERT INTO actor (name, age) VALUES ('Frederic Forrest', 54);
INSERT INTO actor (name, age) VALUES ('Guy Pearce', 41);
INSERT INTO actor (name, age) VALUES ('Carrie Anne Moss', 51);
INSERT INTO actor (name, age) VALUES ('Joe Pantoliano', 21);
INSERT INTO actor (name, age) VALUES ('Mark Boone Junior', 28);
INSERT INTO actor (name, age) VALUES ('Charles Chaplin', 25);
INSERT INTO actor (name, age) VALUES ('Jack Oakie', 44);
INSERT INTO actor (name, age) VALUES ('Reginald Gardiner', 55);
INSERT INTO actor (name, age) VALUES ('Henry Daniell', 60);
INSERT INTO actor (name, age) VALUES ('William Holden', 45);
INSERT INTO actor (name, age) VALUES ('Gloria Swanson', 20);
INSERT INTO actor (name, age) VALUES ('Erich von Stroheim', 45);
INSERT INTO actor (name, age) VALUES ('Nancy Olson', 38);
INSERT INTO actor (name, age) VALUES ('Tom Skerritt', 56);
INSERT INTO actor (name, age) VALUES ('Sigourney Weaver', 28);
INSERT INTO actor (name, age) VALUES ('Veronica Cartwright', 35);
INSERT INTO actor (name, age) VALUES ('Harry Dean Stanton', 47);
INSERT INTO actor (name, age) VALUES ('Peter Sellers', 29);
INSERT INTO actor (name, age) VALUES ('George C  Scott', 39);
INSERT INTO actor (name, age) VALUES ('Sterling Hayden', 29);
INSERT INTO actor (name, age) VALUES ('Keenan Wynn', 31);
INSERT INTO actor (name, age) VALUES ('Kirk Douglas', 36);
INSERT INTO actor (name, age) VALUES ('Ralph Meeker', 29);
INSERT INTO actor (name, age) VALUES ('Adolphe Menjou', 33);
INSERT INTO actor (name, age) VALUES ('George Macready', 53);
INSERT INTO actor (name, age) VALUES ('Jamie Foxx', 34);
INSERT INTO actor (name, age) VALUES ('Christoph Waltz', 54);
INSERT INTO actor (name, age) VALUES ('Leonardo DiCaprio', 23);
INSERT INTO actor (name, age) VALUES ('Kerry Washington', 45);
INSERT INTO actor (name, age) VALUES ('Jack Nicholson', 56);
INSERT INTO actor (name, age) VALUES ('Shelley Duvall', 32);
INSERT INTO actor (name, age) VALUES ('Danny Lloyd', 43);
INSERT INTO actor (name, age) VALUES ('Scatman Crothers', 33);
