INSERT INTO studio (id, name, location) VALUES(1, 'Warner Bros. Pictures', 'UK') ;
INSERT INTO studio (id, name, location) VALUES(2, 'Buena Vista Pictures', 'UK') ;
INSERT INTO studio (id, name, location) VALUES(3, 'Columbia Pictures', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(4, 'Twentieth Century Fox', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(5, 'Newmarket Films', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(6, 'The Weinstein Co.', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(7, '20th Century Fox', 'Germany') ;
INSERT INTO studio (id, name, location) VALUES(8, 'Paramount Pictures', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(9, 'Twentieth Century Fox Home Entertainment', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(10, 'United Artists', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(11, 'Dreamworks Distribution LLC', 'UK') ;
INSERT INTO studio (id, name, location) VALUES(12, 'Gramercy Pictures', 'Germany') ;
INSERT INTO studio (id, name, location) VALUES(13, 'Buena Vista', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(14, 'Sony Pictures', 'UK') ;
INSERT INTO studio (id, name, location) VALUES(15, 'Universal Pictures', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(16, 'TriStar Pictures', 'France') ;
INSERT INTO studio (id, name, location) VALUES(17, 'Criterion Collection', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(18, 'New Line Cinema', 'New Zealand') ;
INSERT INTO studio (id, name, location) VALUES(19, 'Warner Bros.', 'UK') ;
INSERT INTO studio (id, name, location) VALUES(20, 'Liberty Films', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(21, 'Orion Pictures Corporation', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(22, 'Sony Pictures Classics', 'USA') ;
INSERT INTO studio (id, name, location) VALUES(23, 'Focus Features', 'UK') ;
INSERT INTO studio (id, name, location) VALUES(24, 'Miramax Films', 'USA') ;
