INSERT INTO person (id,  name) VALUES (1, 'Tim Robbins');
INSERT INTO actor (id,  age) VALUES (1, 53);
INSERT INTO person (id,  name) VALUES (2, 'Morgan Freeman');
INSERT INTO actor (id,  age) VALUES (2, 28);
INSERT INTO person (id,  name) VALUES (3, 'Bob Gunton');
INSERT INTO actor (id,  age) VALUES (3, 42);
INSERT INTO person (id,  name) VALUES (4, 'William Sadler');
INSERT INTO actor (id,  age) VALUES (4, 55);
INSERT INTO person (id,  name) VALUES (5, 'Marlon Brando');
INSERT INTO actor (id,  age) VALUES (5, 53);
INSERT INTO person (id,  name) VALUES (6, 'Al Pacino');
INSERT INTO actor (id,  age) VALUES (6, 41);
INSERT INTO person (id,  name) VALUES (7, 'James Caan');
INSERT INTO actor (id,  age) VALUES (7, 44);
INSERT INTO person (id,  name) VALUES (8, 'Richard S  Castellano');
INSERT INTO actor (id,  age) VALUES (8, 30);
INSERT INTO person (id,  name) VALUES (9, 'Al Pacino');
INSERT INTO actor (id,  age) VALUES (9, 53);
INSERT INTO person (id,  name) VALUES (10, 'Robert Duvall');
INSERT INTO actor (id,  age) VALUES (10, 44);
INSERT INTO person (id,  name) VALUES (11, 'Diane Keaton');
INSERT INTO actor (id,  age) VALUES (11, 22);
INSERT INTO person (id,  name) VALUES (12, 'Robert De Niro');
INSERT INTO actor (id,  age) VALUES (12, 58);
INSERT INTO person (id,  name) VALUES (13, 'Christian Bale');
INSERT INTO actor (id,  age) VALUES (13, 33);
INSERT INTO person (id,  name) VALUES (14, 'Heath Ledger');
INSERT INTO actor (id,  age) VALUES (14, 23);
INSERT INTO person (id,  name) VALUES (15, 'Aaron Eckhart');
INSERT INTO actor (id,  age) VALUES (15, 48);
INSERT INTO person (id,  name) VALUES (16, 'Michael Caine');
INSERT INTO actor (id,  age) VALUES (16, 28);
INSERT INTO person (id,  name) VALUES (17, 'Martin Balsam');
INSERT INTO actor (id,  age) VALUES (17, 32);
INSERT INTO person (id,  name) VALUES (18, 'John Fiedler');
INSERT INTO actor (id,  age) VALUES (18, 25);
INSERT INTO person (id,  name) VALUES (19, 'Lee J  Cobb');
INSERT INTO actor (id,  age) VALUES (19, 44);
INSERT INTO person (id,  name) VALUES (20, 'E G  Marshall');
INSERT INTO actor (id,  age) VALUES (20, 53);
INSERT INTO person (id,  name) VALUES (21, 'Liam Neeson');
INSERT INTO actor (id,  age) VALUES (21, 38);
INSERT INTO person (id,  name) VALUES (22, 'Ben Kingsley');
INSERT INTO actor (id,  age) VALUES (22, 26);
INSERT INTO person (id,  name) VALUES (23, 'Ralph Fiennes');
INSERT INTO actor (id,  age) VALUES (23, 37);
INSERT INTO person (id,  name) VALUES (24, 'Caroline Goodall');
INSERT INTO actor (id,  age) VALUES (24, 45);
INSERT INTO person (id,  name) VALUES (25, 'Noel Appleby');
INSERT INTO actor (id,  age) VALUES (25, 33);
INSERT INTO person (id,  name) VALUES (26, 'Ali Astin');
INSERT INTO actor (id,  age) VALUES (26, 55);
INSERT INTO person (id,  name) VALUES (27, 'Sean Astin');
INSERT INTO actor (id,  age) VALUES (27, 58);
INSERT INTO person (id,  name) VALUES (28, 'David Aston');
INSERT INTO actor (id,  age) VALUES (28, 48);
INSERT INTO person (id,  name) VALUES (29, 'Tim Roth');
INSERT INTO actor (id,  age) VALUES (29, 49);
INSERT INTO person (id,  name) VALUES (30, 'Amanda Plummer');
INSERT INTO actor (id,  age) VALUES (30, 36);
INSERT INTO person (id,  name) VALUES (31, 'Laura Lovelace');
INSERT INTO actor (id,  age) VALUES (31, 28);
INSERT INTO person (id,  name) VALUES (32, 'John Travolta');
INSERT INTO actor (id,  age) VALUES (32, 40);
INSERT INTO person (id,  name) VALUES (33, 'Edward Norton');
INSERT INTO actor (id,  age) VALUES (33, 58);
INSERT INTO person (id,  name) VALUES (34, 'Brad Pitt');
INSERT INTO actor (id,  age) VALUES (34, 49);
INSERT INTO person (id,  name) VALUES (35, 'Meat Loaf');
INSERT INTO actor (id,  age) VALUES (35, 23);
INSERT INTO person (id,  name) VALUES (36, 'Zach Grenier');
INSERT INTO actor (id,  age) VALUES (36, 40);
INSERT INTO person (id,  name) VALUES (37, 'Alan Howard');
INSERT INTO actor (id,  age) VALUES (37, 59);
INSERT INTO person (id,  name) VALUES (38, 'Noel Appleby');
INSERT INTO actor (id,  age) VALUES (38, 59);
INSERT INTO person (id,  name) VALUES (39, 'Sean Astin');
INSERT INTO actor (id,  age) VALUES (39, 58);
INSERT INTO person (id,  name) VALUES (40, 'Sala Baker');
INSERT INTO actor (id,  age) VALUES (40, 57);
INSERT INTO person (id,  name) VALUES (41, 'Tom Hanks');
INSERT INTO actor (id,  age) VALUES (41, 35);
INSERT INTO person (id,  name) VALUES (42, 'Rebecca Williams');
INSERT INTO actor (id,  age) VALUES (42, 50);
INSERT INTO person (id,  name) VALUES (43, 'Sally Field');
INSERT INTO actor (id,  age) VALUES (43, 30);
INSERT INTO person (id,  name) VALUES (44, 'Michael Conner Humphreys');
INSERT INTO actor (id,  age) VALUES (44, 55);
INSERT INTO person (id,  name) VALUES (45, 'Mark Hamill');
INSERT INTO actor (id,  age) VALUES (45, 47);
INSERT INTO person (id,  name) VALUES (46, 'Harrison Ford');
INSERT INTO actor (id,  age) VALUES (46, 41);
INSERT INTO person (id,  name) VALUES (47, 'Carrie Fisher');
INSERT INTO actor (id,  age) VALUES (47, 34);
INSERT INTO person (id,  name) VALUES (48, 'Billy Dee Williams');
INSERT INTO actor (id,  age) VALUES (48, 39);
INSERT INTO person (id,  name) VALUES (49, 'Leonardo DiCaprio');
INSERT INTO actor (id,  age) VALUES (49, 60);
INSERT INTO person (id,  name) VALUES (50, 'Joseph Gordon Levitt');
INSERT INTO actor (id,  age) VALUES (50, 51);
INSERT INTO person (id,  name) VALUES (51, 'Ellen Page');
INSERT INTO actor (id,  age) VALUES (51, 49);
INSERT INTO person (id,  name) VALUES (52, 'Tom Hardy');
INSERT INTO actor (id,  age) VALUES (52, 26);
INSERT INTO person (id,  name) VALUES (53, 'Bruce Allpress');
INSERT INTO actor (id,  age) VALUES (53, 46);
INSERT INTO person (id,  name) VALUES (54, 'Sean Astin');
INSERT INTO actor (id,  age) VALUES (54, 60);
INSERT INTO person (id,  name) VALUES (55, 'John Bach');
INSERT INTO actor (id,  age) VALUES (55, 46);
INSERT INTO person (id,  name) VALUES (56, 'Sala Baker');
INSERT INTO actor (id,  age) VALUES (56, 20);
INSERT INTO person (id,  name) VALUES (57, 'Michael Berryman');
INSERT INTO actor (id,  age) VALUES (57, 55);
INSERT INTO person (id,  name) VALUES (58, 'Peter Brocco');
INSERT INTO actor (id,  age) VALUES (58, 20);
INSERT INTO person (id,  name) VALUES (59, 'Dean R  Brooks');
INSERT INTO actor (id,  age) VALUES (59, 60);
INSERT INTO person (id,  name) VALUES (60, 'Alonzo Brown');
INSERT INTO actor (id,  age) VALUES (60, 36);
INSERT INTO person (id,  name) VALUES (61, 'Robert De Niro');
INSERT INTO actor (id,  age) VALUES (61, 31);
INSERT INTO person (id,  name) VALUES (62, 'Ray Liotta');
INSERT INTO actor (id,  age) VALUES (62, 41);
INSERT INTO person (id,  name) VALUES (63, 'Joe Pesci');
INSERT INTO actor (id,  age) VALUES (63, 49);
INSERT INTO person (id,  name) VALUES (64, 'Lorraine Bracco');
INSERT INTO actor (id,  age) VALUES (64, 47);
INSERT INTO person (id,  name) VALUES (65, 'Keanu Reeves');
INSERT INTO actor (id,  age) VALUES (65, 25);
INSERT INTO person (id,  name) VALUES (66, 'Laurence Fishburne');
INSERT INTO actor (id,  age) VALUES (66, 60);
INSERT INTO person (id,  name) VALUES (67, 'Carrie Anne Moss');
INSERT INTO actor (id,  age) VALUES (67, 48);
INSERT INTO person (id,  name) VALUES (68, 'Hugo Weaving');
INSERT INTO actor (id,  age) VALUES (68, 32);
INSERT INTO person (id,  name) VALUES (69, 'Mark Hamill');
INSERT INTO actor (id,  age) VALUES (69, 57);
INSERT INTO person (id,  name) VALUES (70, 'Harrison Ford');
INSERT INTO actor (id,  age) VALUES (70, 27);
INSERT INTO person (id,  name) VALUES (71, 'Carrie Fisher');
INSERT INTO actor (id,  age) VALUES (71, 25);
INSERT INTO person (id,  name) VALUES (72, 'Peter Cushing');
INSERT INTO actor (id,  age) VALUES (72, 33);
INSERT INTO person (id,  name) VALUES (73, 'Morgan Freeman');
INSERT INTO actor (id,  age) VALUES (73, 55);
INSERT INTO person (id,  name) VALUES (74, 'Andrew Kevin Walker');
INSERT INTO actor (id,  age) VALUES (74, 60);
INSERT INTO person (id,  name) VALUES (75, 'Kevin Spacey');
INSERT INTO actor (id,  age) VALUES (75, 37);
INSERT INTO person (id,  name) VALUES (76, 'Daniel Zacapa');
INSERT INTO actor (id,  age) VALUES (76, 44);
INSERT INTO person (id,  name) VALUES (77, 'James Stewart');
INSERT INTO actor (id,  age) VALUES (77, 57);
INSERT INTO person (id,  name) VALUES (78, 'Donna Reed');
INSERT INTO actor (id,  age) VALUES (78, 44);
INSERT INTO person (id,  name) VALUES (79, 'Lionel Barrymore');
INSERT INTO actor (id,  age) VALUES (79, 59);
INSERT INTO person (id,  name) VALUES (80, 'Thomas Mitchell');
INSERT INTO actor (id,  age) VALUES (80, 52);
INSERT INTO person (id,  name) VALUES (81, 'Jodie Foster');
INSERT INTO actor (id,  age) VALUES (81, 30);
INSERT INTO person (id,  name) VALUES (82, 'Lawrence A  Bonney');
INSERT INTO actor (id,  age) VALUES (82, 26);
INSERT INTO person (id,  name) VALUES (83, 'Kasi Lemmons');
INSERT INTO actor (id,  age) VALUES (83, 22);
INSERT INTO person (id,  name) VALUES (84, 'Lawrence T  Wrentz');
INSERT INTO actor (id,  age) VALUES (84, 34);
INSERT INTO person (id,  name) VALUES (85, 'Stephen Baldwin');
INSERT INTO actor (id,  age) VALUES (85, 58);
INSERT INTO person (id,  name) VALUES (86, 'Gabriel Byrne');
INSERT INTO actor (id,  age) VALUES (86, 60);
INSERT INTO person (id,  name) VALUES (87, 'Benicio Del Toro');
INSERT INTO actor (id,  age) VALUES (87, 30);
INSERT INTO person (id,  name) VALUES (88, 'Kevin Pollak');
INSERT INTO actor (id,  age) VALUES (88, 33);
INSERT INTO person (id,  name) VALUES (89, 'Jean Reno');
INSERT INTO actor (id,  age) VALUES (89, 33);
INSERT INTO person (id,  name) VALUES (90, 'Gary Oldman');
INSERT INTO actor (id,  age) VALUES (90, 25);
INSERT INTO person (id,  name) VALUES (91, 'Natalie Portman');
INSERT INTO actor (id,  age) VALUES (91, 27);
INSERT INTO person (id,  name) VALUES (92, 'Danny Aiello');
INSERT INTO actor (id,  age) VALUES (92, 32);
INSERT INTO person (id,  name) VALUES (93, 'Tom Hanks');
INSERT INTO actor (id,  age) VALUES (93, 55);
INSERT INTO person (id,  name) VALUES (94, 'Tom Sizemore');
INSERT INTO actor (id,  age) VALUES (94, 41);
INSERT INTO person (id,  name) VALUES (95, 'Edward Burns');
INSERT INTO actor (id,  age) VALUES (95, 28);
INSERT INTO person (id,  name) VALUES (96, 'Barry Pepper');
INSERT INTO actor (id,  age) VALUES (96, 47);
INSERT INTO person (id,  name) VALUES (97, 'Virginia Cherrill');
INSERT INTO actor (id,  age) VALUES (97, 54);
INSERT INTO person (id,  name) VALUES (98, 'Florence Lee');
INSERT INTO actor (id,  age) VALUES (98, 57);
INSERT INTO person (id,  name) VALUES (99, 'Harry Myers');
INSERT INTO actor (id,  age) VALUES (99, 55);
INSERT INTO person (id,  name) VALUES (100, 'Al Ernest Garcia');
INSERT INTO actor (id,  age) VALUES (100, 51);
INSERT INTO person (id,  name) VALUES (101, 'Ellen Burstyn');
INSERT INTO actor (id,  age) VALUES (101, 40);
INSERT INTO person (id,  name) VALUES (102, 'Matthew McConaughey');
INSERT INTO actor (id,  age) VALUES (102, 58);
INSERT INTO person (id,  name) VALUES (103, 'Mackenzie Foy');
INSERT INTO actor (id,  age) VALUES (103, 35);
INSERT INTO person (id,  name) VALUES (104, 'John Lithgow');
INSERT INTO actor (id,  age) VALUES (104, 26);
INSERT INTO person (id,  name) VALUES (105, 'Edward Norton');
INSERT INTO actor (id,  age) VALUES (105, 49);
INSERT INTO person (id,  name) VALUES (106, 'Edward Furlong');
INSERT INTO actor (id,  age) VALUES (106, 57);
INSERT INTO person (id,  name) VALUES (107, 'Beverly D Angelo');
INSERT INTO actor (id,  age) VALUES (107, 27);
INSERT INTO person (id,  name) VALUES (108, 'Jennifer Lien');
INSERT INTO actor (id,  age) VALUES (108, 59);
INSERT INTO person (id,  name) VALUES (109, 'Charles Chaplin');
INSERT INTO actor (id,  age) VALUES (109, 49);
INSERT INTO person (id,  name) VALUES (110, 'Paulette Goddard');
INSERT INTO actor (id,  age) VALUES (110, 42);
INSERT INTO person (id,  name) VALUES (111, 'Henry Bergman');
INSERT INTO actor (id,  age) VALUES (111, 30);
INSERT INTO person (id,  name) VALUES (112, 'Tiny Sandford');
INSERT INTO actor (id,  age) VALUES (112, 29);
INSERT INTO person (id,  name) VALUES (113, 'Humphrey Bogart');
INSERT INTO actor (id,  age) VALUES (113, 21);
INSERT INTO person (id,  name) VALUES (114, 'Ingrid Bergman');
INSERT INTO actor (id,  age) VALUES (114, 28);
INSERT INTO person (id,  name) VALUES (115, 'Paul Henreid');
INSERT INTO actor (id,  age) VALUES (115, 51);
INSERT INTO person (id,  name) VALUES (116, 'Claude Rains');
INSERT INTO actor (id,  age) VALUES (116, 53);
INSERT INTO person (id,  name) VALUES (117, 'Tom Hanks');
INSERT INTO actor (id,  age) VALUES (117, 22);
INSERT INTO person (id,  name) VALUES (118, 'David Morse');
INSERT INTO actor (id,  age) VALUES (118, 49);
INSERT INTO person (id,  name) VALUES (119, 'Michael Clarke Duncan');
INSERT INTO actor (id,  age) VALUES (119, 24);
INSERT INTO person (id,  name) VALUES (120, 'Bonnie Hunt');
INSERT INTO actor (id,  age) VALUES (120, 60);
INSERT INTO person (id,  name) VALUES (121, 'Anthony Perkins');
INSERT INTO actor (id,  age) VALUES (121, 43);
INSERT INTO person (id,  name) VALUES (122, 'Vera Miles');
INSERT INTO actor (id,  age) VALUES (122, 33);
INSERT INTO person (id,  name) VALUES (123, 'John Gavin');
INSERT INTO actor (id,  age) VALUES (123, 34);
INSERT INTO person (id,  name) VALUES (124, 'Janet Leigh');
INSERT INTO actor (id,  age) VALUES (124, 47);
INSERT INTO person (id,  name) VALUES (125, 'Harrison Ford');
INSERT INTO actor (id,  age) VALUES (125, 32);
INSERT INTO person (id,  name) VALUES (126, 'Karen Allen');
INSERT INTO actor (id,  age) VALUES (126, 30);
INSERT INTO person (id,  name) VALUES (127, 'Paul Freeman');
INSERT INTO actor (id,  age) VALUES (127, 59);
INSERT INTO person (id,  name) VALUES (128, 'Ronald Lacey');
INSERT INTO actor (id,  age) VALUES (128, 57);
INSERT INTO person (id,  name) VALUES (129, 'Adrien Brody');
INSERT INTO actor (id,  age) VALUES (129, 46);
INSERT INTO person (id,  name) VALUES (130, 'Emilia Fox');
INSERT INTO actor (id,  age) VALUES (130, 29);
INSERT INTO person (id,  name) VALUES (131, 'Michal Zebrowski');
INSERT INTO actor (id,  age) VALUES (131, 53);
INSERT INTO person (id,  name) VALUES (132, 'Ed Stoppard');
INSERT INTO actor (id,  age) VALUES (132, 60);
INSERT INTO person (id,  name) VALUES (133, 'James Stewart');
INSERT INTO actor (id,  age) VALUES (133, 54);
INSERT INTO person (id,  name) VALUES (134, 'Grace Kelly');
INSERT INTO actor (id,  age) VALUES (134, 36);
INSERT INTO person (id,  name) VALUES (135, 'Wendell Corey');
INSERT INTO actor (id,  age) VALUES (135, 31);
INSERT INTO person (id,  name) VALUES (136, 'Thelma Ritter');
INSERT INTO actor (id,  age) VALUES (136, 55);
INSERT INTO person (id,  name) VALUES (137, 'Leonardo DiCaprio');
INSERT INTO actor (id,  age) VALUES (137, 32);
INSERT INTO person (id,  name) VALUES (138, 'Matt Damon');
INSERT INTO actor (id,  age) VALUES (138, 29);
INSERT INTO person (id,  name) VALUES (139, 'Jack Nicholson');
INSERT INTO actor (id,  age) VALUES (139, 50);
INSERT INTO person (id,  name) VALUES (140, 'Mark Wahlberg');
INSERT INTO actor (id,  age) VALUES (140, 53);
INSERT INTO person (id,  name) VALUES (141, 'Miles Teller');
INSERT INTO actor (id,  age) VALUES (141, 39);
INSERT INTO person (id,  name) VALUES (142, 'J K  Simmons');
INSERT INTO actor (id,  age) VALUES (142, 20);
INSERT INTO person (id,  name) VALUES (143, 'Paul Reiser');
INSERT INTO actor (id,  age) VALUES (143, 35);
INSERT INTO person (id,  name) VALUES (144, 'Melissa Benoist');
INSERT INTO actor (id,  age) VALUES (144, 25);
INSERT INTO person (id,  name) VALUES (145, 'Arnold Schwarzenegger');
INSERT INTO actor (id,  age) VALUES (145, 58);
INSERT INTO person (id,  name) VALUES (146, 'Linda Hamilton');
INSERT INTO actor (id,  age) VALUES (146, 38);
INSERT INTO person (id,  name) VALUES (147, 'Edward Furlong');
INSERT INTO actor (id,  age) VALUES (147, 59);
INSERT INTO person (id,  name) VALUES (148, 'Robert Patrick');
INSERT INTO actor (id,  age) VALUES (148, 36);
INSERT INTO person (id,  name) VALUES (149, 'Michael J  Fox');
INSERT INTO actor (id,  age) VALUES (149, 46);
INSERT INTO person (id,  name) VALUES (150, 'Christopher Lloyd');
INSERT INTO actor (id,  age) VALUES (150, 45);
INSERT INTO person (id,  name) VALUES (151, 'Lea Thompson');
INSERT INTO actor (id,  age) VALUES (151, 50);
INSERT INTO person (id,  name) VALUES (152, 'Crispin Glover');
INSERT INTO actor (id,  age) VALUES (152, 26);
INSERT INTO person (id,  name) VALUES (153, 'Russell Crowe');
INSERT INTO actor (id,  age) VALUES (153, 54);
INSERT INTO person (id,  name) VALUES (154, 'Joaquin Phoenix');
INSERT INTO actor (id,  age) VALUES (154, 29);
INSERT INTO person (id,  name) VALUES (155, 'Connie Nielsen');
INSERT INTO actor (id,  age) VALUES (155, 58);
INSERT INTO person (id,  name) VALUES (156, 'Oliver Reed');
INSERT INTO actor (id,  age) VALUES (156, 46);
INSERT INTO person (id,  name) VALUES (157, 'Rowan Atkinson');
INSERT INTO actor (id,  age) VALUES (157, 59);
INSERT INTO person (id,  name) VALUES (158, 'Matthew Broderick');
INSERT INTO actor (id,  age) VALUES (158, 37);
INSERT INTO person (id,  name) VALUES (159, 'Niketa Calame');
INSERT INTO actor (id,  age) VALUES (159, 24);
INSERT INTO person (id,  name) VALUES (160, 'Jim Cummings');
INSERT INTO actor (id,  age) VALUES (160, 32);
INSERT INTO person (id,  name) VALUES (161, 'Hugh Jackman');
INSERT INTO actor (id,  age) VALUES (161, 31);
INSERT INTO person (id,  name) VALUES (162, 'Christian Bale');
INSERT INTO actor (id,  age) VALUES (162, 54);
INSERT INTO person (id,  name) VALUES (163, 'Michael Caine');
INSERT INTO actor (id,  age) VALUES (163, 57);
INSERT INTO person (id,  name) VALUES (164, 'Piper Perabo');
INSERT INTO actor (id,  age) VALUES (164, 35);
INSERT INTO person (id,  name) VALUES (165, 'Marlon Brando');
INSERT INTO actor (id,  age) VALUES (165, 34);
INSERT INTO person (id,  name) VALUES (166, 'Martin Sheen');
INSERT INTO actor (id,  age) VALUES (166, 58);
INSERT INTO person (id,  name) VALUES (167, 'Robert Duvall');
INSERT INTO actor (id,  age) VALUES (167, 56);
INSERT INTO person (id,  name) VALUES (168, 'Frederic Forrest');
INSERT INTO actor (id,  age) VALUES (168, 26);
INSERT INTO person (id,  name) VALUES (169, 'Guy Pearce');
INSERT INTO actor (id,  age) VALUES (169, 55);
INSERT INTO person (id,  name) VALUES (170, 'Carrie Anne Moss');
INSERT INTO actor (id,  age) VALUES (170, 26);
INSERT INTO person (id,  name) VALUES (171, 'Joe Pantoliano');
INSERT INTO actor (id,  age) VALUES (171, 49);
INSERT INTO person (id,  name) VALUES (172, 'Mark Boone Junior');
INSERT INTO actor (id,  age) VALUES (172, 24);
INSERT INTO person (id,  name) VALUES (173, 'Charles Chaplin');
INSERT INTO actor (id,  age) VALUES (173, 22);
INSERT INTO person (id,  name) VALUES (174, 'Jack Oakie');
INSERT INTO actor (id,  age) VALUES (174, 34);
INSERT INTO person (id,  name) VALUES (175, 'Reginald Gardiner');
INSERT INTO actor (id,  age) VALUES (175, 30);
INSERT INTO person (id,  name) VALUES (176, 'Henry Daniell');
INSERT INTO actor (id,  age) VALUES (176, 34);
INSERT INTO person (id,  name) VALUES (177, 'William Holden');
INSERT INTO actor (id,  age) VALUES (177, 39);
INSERT INTO person (id,  name) VALUES (178, 'Gloria Swanson');
INSERT INTO actor (id,  age) VALUES (178, 27);
INSERT INTO person (id,  name) VALUES (179, 'Erich von Stroheim');
INSERT INTO actor (id,  age) VALUES (179, 31);
INSERT INTO person (id,  name) VALUES (180, 'Nancy Olson');
INSERT INTO actor (id,  age) VALUES (180, 31);
INSERT INTO person (id,  name) VALUES (181, 'Tom Skerritt');
INSERT INTO actor (id,  age) VALUES (181, 51);
INSERT INTO person (id,  name) VALUES (182, 'Sigourney Weaver');
INSERT INTO actor (id,  age) VALUES (182, 49);
INSERT INTO person (id,  name) VALUES (183, 'Veronica Cartwright');
INSERT INTO actor (id,  age) VALUES (183, 54);
INSERT INTO person (id,  name) VALUES (184, 'Harry Dean Stanton');
INSERT INTO actor (id,  age) VALUES (184, 47);
INSERT INTO person (id,  name) VALUES (185, 'Peter Sellers');
INSERT INTO actor (id,  age) VALUES (185, 29);
INSERT INTO person (id,  name) VALUES (186, 'George C  Scott');
INSERT INTO actor (id,  age) VALUES (186, 49);
INSERT INTO person (id,  name) VALUES (187, 'Sterling Hayden');
INSERT INTO actor (id,  age) VALUES (187, 27);
INSERT INTO person (id,  name) VALUES (188, 'Keenan Wynn');
INSERT INTO actor (id,  age) VALUES (188, 30);
INSERT INTO person (id,  name) VALUES (189, 'Kirk Douglas');
INSERT INTO actor (id,  age) VALUES (189, 31);
INSERT INTO person (id,  name) VALUES (190, 'Ralph Meeker');
INSERT INTO actor (id,  age) VALUES (190, 36);
INSERT INTO person (id,  name) VALUES (191, 'Adolphe Menjou');
INSERT INTO actor (id,  age) VALUES (191, 30);
INSERT INTO person (id,  name) VALUES (192, 'George Macready');
INSERT INTO actor (id,  age) VALUES (192, 60);
INSERT INTO person (id,  name) VALUES (193, 'Jamie Foxx');
INSERT INTO actor (id,  age) VALUES (193, 32);
INSERT INTO person (id,  name) VALUES (194, 'Christoph Waltz');
INSERT INTO actor (id,  age) VALUES (194, 59);
INSERT INTO person (id,  name) VALUES (195, 'Leonardo DiCaprio');
INSERT INTO actor (id,  age) VALUES (195, 37);
INSERT INTO person (id,  name) VALUES (196, 'Kerry Washington');
INSERT INTO actor (id,  age) VALUES (196, 28);
INSERT INTO person (id,  name) VALUES (197, 'Jack Nicholson');
INSERT INTO actor (id,  age) VALUES (197, 58);
INSERT INTO person (id,  name) VALUES (198, 'Shelley Duvall');
INSERT INTO actor (id,  age) VALUES (198, 56);
INSERT INTO person (id,  name) VALUES (199, 'Danny Lloyd');
INSERT INTO actor (id,  age) VALUES (199, 24);
INSERT INTO person (id,  name) VALUES (200, 'Scatman Crothers');
INSERT INTO actor (id,  age) VALUES (200, 52);