INSERT INTO director (id, name) VALUES(1, 'Lana Wachowski, Lilly Wachowski') ;
INSERT INTO director (id, name) VALUES(2, 'Milos Forman') ;
INSERT INTO director (id, name) VALUES(3, 'Sidney Lumet') ;
INSERT INTO director (id, name) VALUES(4, 'Tony Kaye') ;
INSERT INTO director (id, name) VALUES(5, 'Bryan Singer') ;
INSERT INTO director (id, name) VALUES(6, 'Frank Darabont') ;
INSERT INTO director (id, name) VALUES(7, 'Jonathan Demme') ;
INSERT INTO director (id, name) VALUES(8, 'Steven Spielberg') ;
INSERT INTO director (id, name) VALUES(9, 'Ridley Scott') ;
INSERT INTO director (id, name) VALUES(10, 'Christopher Nolan') ;
INSERT INTO director (id, name) VALUES(11, 'Peter Jackson') ;
INSERT INTO director (id, name) VALUES(12, 'Stanley Kubrick') ;
INSERT INTO director (id, name) VALUES(13, 'Roman Polanski') ;
INSERT INTO director (id, name) VALUES(14, 'Martin Scorsese') ;
INSERT INTO director (id, name) VALUES(15, 'Luc Besson') ;
INSERT INTO director (id, name) VALUES(16, 'Alfred Hitchcock') ;
INSERT INTO director (id, name) VALUES(17, 'James Cameron') ;
INSERT INTO director (id, name) VALUES(18, 'Charles Chaplin') ;
INSERT INTO director (id, name) VALUES(19, 'Billy Wilder') ;
INSERT INTO director (id, name) VALUES(20, 'David Fincher') ;
INSERT INTO director (id, name) VALUES(21, 'Roger Allers, Rob Minkoff') ;
INSERT INTO director (id, name) VALUES(22, 'Francis Ford Coppola') ;
INSERT INTO director (id, name) VALUES(23, 'Frank Capra') ;
INSERT INTO director (id, name) VALUES(24, 'Irvin Kershner') ;
INSERT INTO director (id, name) VALUES(25, 'Michael Curtiz') ;
INSERT INTO director (id, name) VALUES(26, 'Quentin Tarantino') ;
INSERT INTO director (id, name) VALUES(27, 'Robert Zemeckis') ;
INSERT INTO director (id, name) VALUES(28, 'George Lucas') ;
INSERT INTO director (id, name) VALUES(29, 'Damien Chazelle') ;
