INSERT INTO person (id, name) VALUES(202, 'Christopher Nolan') ;
INSERT INTO director (id, oscars) VALUES(202, 3) ;
INSERT INTO person (id, name) VALUES(203, 'Frank Capra') ;
INSERT INTO director (id, oscars) VALUES(203, 1) ;
INSERT INTO person (id, name) VALUES(204, 'Billy Wilder') ;
INSERT INTO director (id, oscars) VALUES(204, 3) ;
INSERT INTO person (id, name) VALUES(205, 'Sidney Lumet') ;
INSERT INTO director (id, oscars) VALUES(205, 1) ;
INSERT INTO person (id, name) VALUES(206, 'Peter Jackson') ;
INSERT INTO director (id, oscars) VALUES(206, 4) ;
INSERT INTO person (id, name) VALUES(207, 'Martin Scorsese') ;
INSERT INTO director (id, oscars) VALUES(207, 2) ;
INSERT INTO person (id, name) VALUES(208, 'James Cameron') ;
INSERT INTO director (id, oscars) VALUES(208, 2) ;
INSERT INTO person (id, name) VALUES(209, 'George Lucas') ;
INSERT INTO director (id, oscars) VALUES(209, 1) ;
INSERT INTO person (id, name) VALUES(210, 'Michael Curtiz') ;
INSERT INTO director (id, oscars) VALUES(210, 1) ;
INSERT INTO person (id, name) VALUES(211, 'Tony Kaye') ;
INSERT INTO director (id, oscars) VALUES(211, 1) ;
INSERT INTO person (id, name) VALUES(212, 'Frank Darabont') ;
INSERT INTO director (id, oscars) VALUES(212, 0) ;
INSERT INTO person (id, name) VALUES(213, 'Robert Zemeckis') ;
INSERT INTO director (id, oscars) VALUES(213, 0) ;
INSERT INTO person (id, name) VALUES(214, 'Charles Chaplin') ;
INSERT INTO director (id, oscars) VALUES(214, 1) ;
INSERT INTO person (id, name) VALUES(215, 'Roger Allers, Rob Minkoff') ;
INSERT INTO director (id, oscars) VALUES(215, 3) ;
INSERT INTO person (id, name) VALUES(216, 'Francis Ford Coppola') ;
INSERT INTO director (id, oscars) VALUES(216, 2) ;
INSERT INTO person (id, name) VALUES(217, 'Steven Spielberg') ;
INSERT INTO director (id, oscars) VALUES(217, 2) ;
INSERT INTO person (id, name) VALUES(218, 'Luc Besson') ;
INSERT INTO director (id, oscars) VALUES(218, 0) ;
INSERT INTO person (id, name) VALUES(219, 'Damien Chazelle') ;
INSERT INTO director (id, oscars) VALUES(219, 4) ;
INSERT INTO person (id, name) VALUES(220, 'Bryan Singer') ;
INSERT INTO director (id, oscars) VALUES(220, 2) ;
INSERT INTO person (id, name) VALUES(221, 'Jonathan Demme') ;
INSERT INTO director (id, oscars) VALUES(221, 0) ;
INSERT INTO person (id, name) VALUES(222, 'Stanley Kubrick') ;
INSERT INTO director (id, oscars) VALUES(222, 4) ;
INSERT INTO person (id, name) VALUES(223, 'Irvin Kershner') ;
INSERT INTO director (id, oscars) VALUES(223, 4) ;
INSERT INTO person (id, name) VALUES(224, 'Lana Wachowski, Lilly Wachowski') ;
INSERT INTO director (id, oscars) VALUES(224, 0) ;
INSERT INTO person (id, name) VALUES(225, 'Roman Polanski') ;
INSERT INTO director (id, oscars) VALUES(225, 0) ;
INSERT INTO person (id, name) VALUES(226, 'David Fincher') ;
INSERT INTO director (id, oscars) VALUES(226, 3) ;
INSERT INTO person (id, name) VALUES(227, 'Quentin Tarantino') ;
INSERT INTO director (id, oscars) VALUES(227, 1) ;
INSERT INTO person (id, name) VALUES(228, 'Ridley Scott') ;
INSERT INTO director (id, oscars) VALUES(228, 2) ;
INSERT INTO person (id, name) VALUES(229, 'Alfred Hitchcock') ;
INSERT INTO director (id, oscars) VALUES(229, 0) ;
INSERT INTO person (id, name) VALUES(230, 'Milos Forman') ;
INSERT INTO director (id, oscars) VALUES(230, 3) ;
